# ---------------------------------------------  Server Port ------------------------------------------------------- #
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}


spring:
  application:
    name: ai
# --------------------------------------------- Redis NoSQL Database    -----------------------------------#
  redis:
    host: 127.0.0.1
#    host: 192.168.1.3
    port: 6379
    database: 1
    password:
    #lettuce连接池配置
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-active: 8


baidu:
  appid: your appid
  appkey: your appkey
  secret: your secret